---
- name: Setup NGINX Container
  hosts: local
  gather_facts: false
  
  tasks:
    - name: Ensure python docker package is installed
      pip:
        name: docker
        state: present
      
    - name: Create NGINX container
      docker_container:
        name: nginx-server
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - "{{ playbook_dir }}/html:/usr/share/nginx/html"
      register: container_result
      environment:
        DOCKER_HOST: "unix:///var/run/docker.sock"
    
    - name: Display container info
      debug:
        var: container_result