---
- name: Setup NGINX Container
  hosts: local
  gather_facts: false
  
  tasks:
    # Remove the pip install task since we're using system package
    - name: Create NGINX container
      docker_container:
        name: nginx-server
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - "{{ playbook_dir }}/html:/usr/share/nginx/html"
      environment:
        DOCKER_HOST: "unix:///var/run/docker.sock"
      register: container_result
    
    - name: Display container info
      debug:
        var: container_result